// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: rhombic/acl/adapters/pl/dto/uuid.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UUIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UUIDRequest) Reset() {
	*x = UUIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDRequest) ProtoMessage() {}

func (x *UUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDRequest.ProtoReflect.Descriptor instead.
func (*UUIDRequest) Descriptor() ([]byte, []int) {
	return file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescGZIP(), []int{0}
}

type UUIDRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (x *UUIDRespond) Reset() {
	*x = UUIDRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UUIDRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDRespond) ProtoMessage() {}

func (x *UUIDRespond) ProtoReflect() protoreflect.Message {
	mi := &file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDRespond.ProtoReflect.Descriptor instead.
func (*UUIDRespond) Descriptor() ([]byte, []int) {
	return file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescGZIP(), []int{1}
}

func (x *UUIDRespond) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

var File_rhombic_acl_adapters_pl_dto_uuid_proto protoreflect.FileDescriptor

var file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDesc = []byte{
	0x0a, 0x26, 0x72, 0x68, 0x6f, 0x6d, 0x62, 0x69, 0x63, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x6c, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x75, 0x75,
	0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x74, 0x6f, 0x22, 0x0d, 0x0a,
	0x0b, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x21, 0x0a, 0x0b,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x55,
	0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x32,
	0x3e, 0x0a, 0x0b, 0x55, 0x55, 0x49, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x10, 0x2e, 0x64, 0x74, 0x6f, 0x2e,
	0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x64, 0x74,
	0x6f, 0x2e, 0x55, 0x55, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescOnce sync.Once
	file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescData = file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDesc
)

func file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescGZIP() []byte {
	file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescOnce.Do(func() {
		file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescData)
	})
	return file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDescData
}

var file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rhombic_acl_adapters_pl_dto_uuid_proto_goTypes = []interface{}{
	(*UUIDRequest)(nil), // 0: dto.UUIDRequest
	(*UUIDRespond)(nil), // 1: dto.UUIDRespond
}
var file_rhombic_acl_adapters_pl_dto_uuid_proto_depIdxs = []int32{
	0, // 0: dto.UUIDService.GetUUID:input_type -> dto.UUIDRequest
	1, // 1: dto.UUIDService.GetUUID:output_type -> dto.UUIDRespond
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rhombic_acl_adapters_pl_dto_uuid_proto_init() }
func file_rhombic_acl_adapters_pl_dto_uuid_proto_init() {
	if File_rhombic_acl_adapters_pl_dto_uuid_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UUIDRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rhombic_acl_adapters_pl_dto_uuid_proto_goTypes,
		DependencyIndexes: file_rhombic_acl_adapters_pl_dto_uuid_proto_depIdxs,
		MessageInfos:      file_rhombic_acl_adapters_pl_dto_uuid_proto_msgTypes,
	}.Build()
	File_rhombic_acl_adapters_pl_dto_uuid_proto = out.File
	file_rhombic_acl_adapters_pl_dto_uuid_proto_rawDesc = nil
	file_rhombic_acl_adapters_pl_dto_uuid_proto_goTypes = nil
	file_rhombic_acl_adapters_pl_dto_uuid_proto_depIdxs = nil
}
