// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: rhombic/acl/adapters/pl/dto/uuid.proto

package dto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UUIDServiceClient is the client API for UUIDService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UUIDServiceClient interface {
	GetUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDRespond, error)
}

type uUIDServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUUIDServiceClient(cc grpc.ClientConnInterface) UUIDServiceClient {
	return &uUIDServiceClient{cc}
}

func (c *uUIDServiceClient) GetUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*UUIDRespond, error) {
	out := new(UUIDRespond)
	err := c.cc.Invoke(ctx, "/dto.UUIDService/GetUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UUIDServiceServer is the server API for UUIDService service.
// All implementations must embed UnimplementedUUIDServiceServer
// for forward compatibility
type UUIDServiceServer interface {
	GetUUID(context.Context, *UUIDRequest) (*UUIDRespond, error)
	mustEmbedUnimplementedUUIDServiceServer()
}

// UnimplementedUUIDServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUUIDServiceServer struct {
}

func (UnimplementedUUIDServiceServer) GetUUID(context.Context, *UUIDRequest) (*UUIDRespond, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUUID not implemented")
}
func (UnimplementedUUIDServiceServer) mustEmbedUnimplementedUUIDServiceServer() {}

// UnsafeUUIDServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UUIDServiceServer will
// result in compilation errors.
type UnsafeUUIDServiceServer interface {
	mustEmbedUnimplementedUUIDServiceServer()
}

func RegisterUUIDServiceServer(s grpc.ServiceRegistrar, srv UUIDServiceServer) {
	s.RegisterService(&UUIDService_ServiceDesc, srv)
}

func _UUIDService_GetUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UUIDServiceServer).GetUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dto.UUIDService/GetUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UUIDServiceServer).GetUUID(ctx, req.(*UUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UUIDService_ServiceDesc is the grpc.ServiceDesc for UUIDService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UUIDService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dto.UUIDService",
	HandlerType: (*UUIDServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUUID",
			Handler:    _UUIDService_GetUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rhombic/acl/adapters/pl/dto/uuid.proto",
}
