// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.0
// source: diamond/acl/adapters/pl/dto/space.proto

package dto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrganizationID string `protobuf:"bytes,1,opt,name=OrganizationID,proto3" json:"OrganizationID,omitempty"`
}

func (x *SpaceRequest) Reset() {
	*x = SpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRequest) ProtoMessage() {}

func (x *SpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRequest.ProtoReflect.Descriptor instead.
func (*SpaceRequest) Descriptor() ([]byte, []int) {
	return file_rhombic_acl_adapters_pl_dto_space_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceRequest) GetOrganizationID() string {
	if x != nil {
		return x.OrganizationID
	}
	return ""
}

type SpaceRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Space []*SpaceValueObject `protobuf:"bytes,1,rep,name=space,proto3" json:"space,omitempty"`
}

func (x *SpaceRespond) Reset() {
	*x = SpaceRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceRespond) ProtoMessage() {}

func (x *SpaceRespond) ProtoReflect() protoreflect.Message {
	mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceRespond.ProtoReflect.Descriptor instead.
func (*SpaceRespond) Descriptor() ([]byte, []int) {
	return file_rhombic_acl_adapters_pl_dto_space_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceRespond) GetSpace() []*SpaceValueObject {
	if x != nil {
		return x.Space
	}
	return nil
}

type SpaceValueObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Owner    string `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Manager  bool   `protobuf:"varint,3,opt,name=Manager,proto3" json:"Manager,omitempty"`
	Seat     int32  `protobuf:"varint,4,opt,name=Seat,proto3" json:"Seat,omitempty"`
	Capacity int32  `protobuf:"varint,5,opt,name=Capacity,proto3" json:"Capacity,omitempty"`
}

func (x *SpaceValueObject) Reset() {
	*x = SpaceValueObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceValueObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceValueObject) ProtoMessage() {}

func (x *SpaceValueObject) ProtoReflect() protoreflect.Message {
	mi := &file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceValueObject.ProtoReflect.Descriptor instead.
func (*SpaceValueObject) Descriptor() ([]byte, []int) {
	return file_rhombic_acl_adapters_pl_dto_space_proto_rawDescGZIP(), []int{2}
}

func (x *SpaceValueObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SpaceValueObject) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *SpaceValueObject) GetManager() bool {
	if x != nil {
		return x.Manager
	}
	return false
}

func (x *SpaceValueObject) GetSeat() int32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *SpaceValueObject) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_rhombic_acl_adapters_pl_dto_space_proto protoreflect.FileDescriptor

var file_rhombic_acl_adapters_pl_dto_space_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x68, 0x6f, 0x6d, 0x62, 0x69, 0x63, 0x2f, 0x61, 0x63, 0x6c, 0x2f, 0x61, 0x64,
	0x61, 0x70, 0x74, 0x65, 0x72, 0x73, 0x2f, 0x70, 0x6c, 0x2f, 0x64, 0x74, 0x6f, 0x2f, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x74, 0x6f, 0x22, 0x36,
	0x0a, 0x0c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x26,
	0x0a, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x4f, 0x72, 0x67, 0x61, 0x6e, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x22, 0x3b, 0x0a, 0x0c, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x53, 0x70, 0x61, 0x63,
	0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x05, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x10, 0x53, 0x70, 0x61, 0x63, 0x65, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x4f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x65, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x53, 0x65, 0x61, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x43, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x32, 0x41, 0x0a, 0x0c,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x07,
	0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x64, 0x74, 0x6f,
	0x2e, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_rhombic_acl_adapters_pl_dto_space_proto_rawDescOnce sync.Once
	file_rhombic_acl_adapters_pl_dto_space_proto_rawDescData = file_rhombic_acl_adapters_pl_dto_space_proto_rawDesc
)

func file_rhombic_acl_adapters_pl_dto_space_proto_rawDescGZIP() []byte {
	file_rhombic_acl_adapters_pl_dto_space_proto_rawDescOnce.Do(func() {
		file_rhombic_acl_adapters_pl_dto_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_rhombic_acl_adapters_pl_dto_space_proto_rawDescData)
	})
	return file_rhombic_acl_adapters_pl_dto_space_proto_rawDescData
}

var file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rhombic_acl_adapters_pl_dto_space_proto_goTypes = []interface{}{
	(*SpaceRequest)(nil),     // 0: dto.SpaceRequest
	(*SpaceRespond)(nil),     // 1: dto.SpaceRespond
	(*SpaceValueObject)(nil), // 2: dto.SpaceValueObject
}
var file_rhombic_acl_adapters_pl_dto_space_proto_depIdxs = []int32{
	2, // 0: dto.SpaceRespond.space:type_name -> dto.SpaceValueObject
	0, // 1: dto.SpaceService.GetList:input_type -> dto.SpaceRequest
	1, // 2: dto.SpaceService.GetList:output_type -> dto.SpaceRespond
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rhombic_acl_adapters_pl_dto_space_proto_init() }
func file_rhombic_acl_adapters_pl_dto_space_proto_init() {
	if File_rhombic_acl_adapters_pl_dto_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceValueObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rhombic_acl_adapters_pl_dto_space_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rhombic_acl_adapters_pl_dto_space_proto_goTypes,
		DependencyIndexes: file_rhombic_acl_adapters_pl_dto_space_proto_depIdxs,
		MessageInfos:      file_rhombic_acl_adapters_pl_dto_space_proto_msgTypes,
	}.Build()
	File_rhombic_acl_adapters_pl_dto_space_proto = out.File
	file_rhombic_acl_adapters_pl_dto_space_proto_rawDesc = nil
	file_rhombic_acl_adapters_pl_dto_space_proto_goTypes = nil
	file_rhombic_acl_adapters_pl_dto_space_proto_depIdxs = nil
}
